#spring:
#  profiles:
#    active: "dev"
#  main:
#    banner-mode: "off"
#
#
#---
#
#spring:
#  profiles: dev
#server:
#  email: dev@mkyong.com
#  cluster:
#    - ip: 127.0.0.1
#      path: /dev1
#    - ip: 127.0.0.2
#      path: /dev2
#    - ip: 127.0.0.3
#      path: /dev3
#
#---
#
#spring:
#  profiles: prod
#server:
#  email: prod@mkyong.com
#  cluster:
#    - ip: 192.168.0.1
#      path: /app1
#    - ip: 192.168.0.2
#      path: /app2
#    - ip: 192.168.0.3
#      path: /app3
#
#---
#
#
spring:
  rabbitmq:
    host: 10.178.0.7
    username: guest
    password: guest
    port: 5672
  data:
    elasticsearch:
      host: 10.146.0.3,10.146.0.4,10.146.0.5,10.146.0.6
      port: 9200
#
#---
#
#spring:
#  profiles:
#    active:
#      default logging:
#        level:
#          root: debug
#
#---
#
#spring:
#  profiles:
#    dev logging:
#      level:
#        root: info
#
#---
#
#spring:
#  profiles:
#    test logging:
#      level:
#        root: debug
#      level.org.hibernate:
#        SQL: debug
#        type.descriptor.sql.BasicBinder: trace